# Generated by Django 3.2.4 on 2021-06-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_password',
            field=models.CharField(default='', max_length=21),
        ),
    ]
